#!/usr/bin/env bash
# Regenerates docs/STATUS.md from live codebase state.
# Run manually: bash scripts/update-docs.sh
# Or hook into git via: echo 'bash scripts/update-docs.sh && git add docs/STATUS.md' >> .git/hooks/post-commit

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
STATUS_FILE="$REPO_ROOT/docs/STATUS.md"

LAST_COMMIT=$(git log -1 --format="%h")
LAST_MSG=$(git log -1 --format="%s")
LAST_DATE=$(git log -1 --format="%ci")
BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMMIT_COUNT=$(git rev-list --count HEAD)

NEXT_VER=$(node -p "require('./package.json').dependencies.next" 2>/dev/null || echo "unknown")
REACT_VER=$(node -p "require('./package.json').dependencies.react" 2>/dev/null || echo "unknown")

ROUTES=$(find "$REPO_ROOT/app" -name "page.tsx" -o -name "route.ts" 2>/dev/null | \
  sed "s|$REPO_ROOT/app||" | sed 's|/page\.tsx||' | sed 's|/route\.ts| (API)|' | \
  sed 's|(portal)/||' | sed 's|(marketing)/||' | sort)

cat > "$STATUS_FILE" << EOF
# BRT Inc. — Project Status

> Auto-generated by \`scripts/update-docs.sh\`. Do not edit manually.

**Last updated:** $(date -u '+%Y-%m-%d %H:%M UTC')

## Deployment

| | |
|---|---|
| **Production** | https://brtinc.dev |
| **Vercel project** | brt-inc (sir-charles-projects team) |
| **Latest deployment** | https://vercel.com/sir-charles-projects/brt-inc |
| **GitHub repo** | https://github.com/CBahtaria/brt-inc |

## Build

| | |
|---|---|
| **Branch** | \`$BRANCH\` |
| **Commits** | $COMMIT_COUNT |
| **Last commit** | \`$LAST_COMMIT\` — $LAST_MSG |
| **Commit date** | $LAST_DATE |
| **Next.js** | $NEXT_VER |
| **React** | $REACT_VER |

## Routes

\`\`\`
$(echo "$ROUTES" | sed 's/^/  /')
\`\`\`

## Recent Changes

$(git log --oneline -10 | sed 's/^/- /')

## Portal Pages

| Route | Component | Data source |
|---|---|---|
| /dashboard | PortalShell | Static |
| /crm | CRMTable | Supabase \`clients\` |
| /proposals | ProposalEditor | Supabase \`proposals\` + \`clients\` |
| /invoices | InvoiceBuilder | Supabase \`invoices\` |
| /runbooks | RunbookList | Supabase \`runbook_templates\` |
| /status | StatusGrid | Live polls (30s interval) |
| /assets | AssetGenerator | Higgsfield AI REST API |

## API Routes

| Route | Method | Auth | Purpose |
|---|---|---|---|
| /api/contact | POST | None | Contact form → Resend email |
| /api/send-email | POST | Supabase Bearer | Internal email (proposals, invoices) |
| /api/generate | POST | Supabase session | Submit Higgsfield generation job |
| /api/generate/[jobId] | GET | Supabase session | Poll Higgsfield job status |
| /api/healthcheck | GET, HEAD | None | StatusGrid service check |
| /api/stripe-webhook | POST | Stripe signature | Payment events (stub) |

## Open Items

- [ ] Add \`HIGGSFIELD_API_KEY\` to Vercel environment variables
- [ ] Verify \`brtinc.dev\` DNS propagation complete
- [ ] Remove or reassign \`brt-inc.vercel.app\` (personal Vercel account) via dashboard
- [ ] Implement ProposalEditor, InvoiceBuilder (Phase 5.4 stubs)
- [ ] Port Stripe webhook logic from \`api/stripe-webhook.js\`
EOF

echo "✓ docs/STATUS.md updated"
